// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, game;

  game = require('./models/deuces2');

  express = require('express');

  app = express();

  app.get('/', function(req, res) {
    var body;
    body = "Hello world";
    res.setHeader("Content-Type", "text/plain");
    res.setHeader("Content-Length", body.length);
    return res.end(body);
  });

  app.listen(3000);

}).call(this);
