// Generated by CoffeeScript 1.6.3
(function() {
  var Card, Ranks, _;

  Ranks = require("./ranks");

  _ = require("./lib/underscore-min");

  Card = (function() {
    function Card(rank, suit) {
      this.rank = rank;
      this.suit = suit;
    }

    Card.prototype.numericalRank = function() {
      var numericalRankDictionary;
      numericalRankDictionary = _.invert(Ranks);
      return parseInt(numericalRankDictionary[this.rank], 10);
    };

    return Card;

  })();

  module.exports = Card;

}).call(this);
