// Generated by CoffeeScript 1.6.3
(function() {
  var Card, Deck, Ranks, Suits, _,
    __hasProp = {}.hasOwnProperty;

  Ranks = require("./ranks");

  Suits = require("./suits");

  Card = require("./card");

  _ = require("./lib/underscore-min");

  Deck = (function() {
    function Deck() {
      var rank, rank_num, suit, suit_num;
      this.cards = [];
      for (rank_num in Ranks) {
        if (!__hasProp.call(Ranks, rank_num)) continue;
        rank = Ranks[rank_num];
        for (suit_num in Suits) {
          if (!__hasProp.call(Suits, suit_num)) continue;
          suit = Suits[suit_num];
          this.cards.push(new Card(rank, suit));
        }
      }
    }

    Deck.prototype.shuffle = function() {
      return this.cards = _.shuffle(this.cards);
    };

    return Deck;

  })();

  module.exports = Deck;

}).call(this);
