// Generated by CoffeeScript 1.6.3
(function() {
  var Card, Deck, Game, Player, Ranks, Suits, _,
    __hasProp = {}.hasOwnProperty;

  _ = require("./lib/underscore-min");

  Ranks = {
    0: 3,
    1: 4,
    2: 5,
    3: 6,
    4: 7,
    5: 8,
    6: 9,
    7: 10,
    8: "J",
    9: "Q",
    10: "K",
    11: "A",
    12: 2
  };

  Suits = {
    0: "Diamond",
    1: "Club",
    2: "Hearts",
    3: "Spade"
  };

  Game = (function() {
    function Game() {
      this.deck = new Deck();
      this.players = [];
    }

    Game.prototype.addPlayer = function(player) {
      if (player instanceof Player && this.players.length < 4) {
        return this.players.push(player);
      }
    };

    return Game;

  })();

  Deck = (function() {
    function Deck() {
      var rank, rank_num, suit, suit_num;
      this.cards = [];
      for (rank_num in Ranks) {
        if (!__hasProp.call(Ranks, rank_num)) continue;
        rank = Ranks[rank_num];
        for (suit_num in Suits) {
          if (!__hasProp.call(Suits, suit_num)) continue;
          suit = Suits[suit_num];
          this.cards.push(new Card(rank, suit));
        }
      }
    }

    return Deck;

  })();

  Player = (function() {
    function Player() {}

    return Player;

  })();

  Card = (function() {
    function Card(rank, suit) {
      this.rank = rank;
      this.suits = suit;
    }

    return Card;

  })();

  exports.Card = Card;

  exports.Game = Game;

  exports.Player = Player;

}).call(this);
