// Generated by CoffeeScript 1.6.3
(function() {
  var Player;

  Player = (function() {
    function Player() {
      this.hand = [];
      this.game = null;
      this.id = Math.floor(Math.random() * 10000000);
    }

    Player.prototype.playCards = function(cards) {
      return game.processTurn(this.id, cards);
    };

    return Player;

  })();

  module.exports = Player;

}).call(this);
