// Generated by CoffeeScript 1.6.3
(function() {
  var Ranks;

  Ranks = {
    0: 3,
    1: 4,
    2: 5,
    3: 6,
    4: 7,
    5: 8,
    6: 9,
    7: 10,
    8: "J",
    9: "Q",
    10: "K",
    11: "A",
    12: 2
  };

  module.exports = Ranks;

}).call(this);
