// Generated by CoffeeScript 1.6.3
(function() {
  var Room;

  Room = (function() {
    function Room(name) {
      var game, players;
      this.name = name;
      players = [];
      game = {};
    }

    return Room;

  })();

}).call(this);
